name: Notify users based on issue labels

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.2
          with:
             token: ${{ secrets.GITHUB_TOKEN }}
             recipients: |
               Admin & management=@SCRC-admin
               Contact-Tracing-Model=@FMD-Model
               CoronaBICI=@CoronaBICI
               Covid_Simulation_Model=@NDCode
               Covid19_EERAModel=@EERAModel
               Data management=@SCRC-data
               model reconstruction=@Model-reconstruction
               Simple Network Sim=@Simple-Network-Sim
               Simulation.jl=@Simulation-jl-devs @Simulation-jl-admins
