name: Notify users based on issue labels

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.2
          with:
             token: ${{ secrets.GITHUB_TOKEN }}
             recipients: |
               Admin & management=@alysbrett @richardreeve
               Contact-Tracing-Model=@sibylleM @johnnonweiler @sam-brett
               CoronaBICI=@chrispooley @ianhinder
               Covid_Simulation_Model=@paulbessell @johnnonweiler @bobtaylor12
               Covid19_EERAModel=@thibaud-porphyre @peter-t-fox
               Data management=@IainM-BioSS
               model reconstruction=@kzscisoft @richardreeve
               Simple Network Sim=@magicicada @bobturneruk
               Simulation.jl=@claireh93 @richardreeve @jwscook
