name: Notify users based on issue labels

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.2
          with:
             token: ${{ secrets.GITHUB_TOKEN }}
             recipients: |
               Admin & management=@alysbrett @richardreeve
               Contact-Tracing-Model=@sibylleM @johnnonweiler @sam-brett @vinopm
               BEEPmbp=@chrispooley @ianhinder @rwj11
               Covid_Simulation_Model=@paulbessell @johnnonweiler
               Covid19_EERAModel=@thibaud-porphyre @peter-t-fox
               Data management=@IainM-BioSS @aaron-reeves
               model reconstruction=@kzscisoft @richardreeve
               Simple Network Sim=@magicicada @bobturneruk @aflag @WPettersson @alex-konovalov @may1066 @mrow84
               Simulation.jl=@claireh93 @richardreeve @jwscook @sdl1 @wytbella
               interoperability=@alysbrett @richardreeve
               data pipeline api=@mrow84 @bobturneruk
