name: Notify users based on issue labels

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.2
          with:
             token: ${{ secrets.GITHUB_TOKEN }}
             recipients: |
               Admin & management=@ScottishCovidResponse/SCRC-admin
               Contact-Tracing-Model=@ScottishCovidResponse/FMD-Model
               CoronaBICI=@ScottishCovidResponse/CoronaBICI
               Covid_Simulation_Model=@ScottishCovidResponse/NDCode
               Covid19_EERAModel=@ScottishCovidResponse/EERAModel
               Data management=@ScottishCovidResponse/SCRC-data
               model reconstruction=@ScottishCovidResponse/Model-reconstruction
               Simple Network Sim=@ScottishCovidResponse/Simple-Network-Sim
               Simulation.jl=@ScottishCovidResponse/Simulation-jl-devs @ScottishCovidResponse/Simulation-jl-admins
